import bcrypt from "bcryptjs";
import pg from "pg";
import type { PoolClient, QueryResultRow } from "pg";

const { Pool } = pg;

type QueryExecutor = PoolClient;

let pool: pg.Pool;

function envFlag(value: string | undefined, defaultValue: boolean) {
  if (value === undefined) return defaultValue;
  return ["1", "true", "yes", "sim"].includes(value.trim().toLowerCase());
}

function connectionConfig(): pg.PoolConfig {
  const connectionString = process.env.DATABASE_URL;

  if (connectionString) {
    return {
      connectionString,
      max: Number(process.env.DB_POOL_MAX ?? 10),
      ssl: envFlag(process.env.DB_SSL, process.env.NODE_ENV === "production")
        ? { rejectUnauthorized: false }
        : undefined,
    };
  }

  return {
    host: process.env.DB_HOST ?? "localhost",
    port: Number(process.env.DB_PORT ?? 5432),
    database: process.env.DB_NAME ?? "compras_senai",
    user: process.env.DB_USER ?? "postgres",
    password: process.env.DB_PASSWORD ?? "postgres",
    max: Number(process.env.DB_POOL_MAX ?? 10),
  };
}

function prepareStatement(statement: string, parameters: Record<string, unknown>) {
  const values: unknown[] = [];
  const indexes = new Map<string, number>();
  const text = statement
    .replace(/N'/g, "'")
    .replace(/@([a-zA-Z_]\w*)/g, (_match, name: string) => {
      if (!indexes.has(name)) {
        indexes.set(name, values.push(parameters[name]));
      }
      return `$${indexes.get(name)}`;
    });

  return { text, values };
}

export async function query<T extends QueryResultRow = QueryResultRow>(
  statement: string,
  parameters: Record<string, unknown> = {},
  executor?: QueryExecutor,
) {
  if (!executor && !pool) {
    throw new Error("O banco de dados ainda nao foi inicializado.");
  }

  const { text, values } = prepareStatement(statement, parameters);
  const result = await (executor ?? pool).query<T>(text, values);
  return result.rows;
}

export async function withTransaction<T>(work: (transaction: QueryExecutor) => Promise<T>) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    const result = await work(client);
    await client.query("COMMIT");
    return result;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function initDatabase() {
  pool = new Pool(connectionConfig());
  await pool.query("SELECT 1");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      email VARCHAR(160) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('professor', 'coordenacao')),
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    ALTER TABLE users
      ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

    CREATE TABLE IF NOT EXISTS cost_centers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code VARCHAR(40) NOT NULL UNIQUE,
      name VARCHAR(140) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS catalog_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code VARCHAR(80) NOT NULL UNIQUE,
      description TEXT NOT NULL,
      cost_center_id INTEGER NULL REFERENCES cost_centers(id),
      source VARCHAR(40) NOT NULL DEFAULT 'planilha',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS purchase_requests (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      professor_id INTEGER NOT NULL REFERENCES users(id),
      catalog_item_id INTEGER NULL REFERENCES catalog_items(id),
      cost_center_id INTEGER NOT NULL REFERENCES cost_centers(id),
      item_type VARCHAR(20) NOT NULL CHECK (item_type IN ('catalogo', 'novo')),
      quantity INTEGER NOT NULL CHECK (quantity > 0),
      justification TEXT NOT NULL,
      new_item_name VARCHAR(180) NULL,
      new_item_description TEXT NULL,
      supplier_link TEXT NULL,
      status VARCHAR(40) NOT NULL CHECK (
        status IN ('aguardando_coordenacao', 'novo_item_pendente', 'aprovada', 'recusada', 'ajuste_solicitado')
      ),
      coordinator_response TEXT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS request_attachments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      request_id INTEGER NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
      kind VARCHAR(30) NOT NULL CHECK (kind IN ('ficha_tecnica', 'foto')),
      original_name VARCHAR(220) NOT NULL,
      stored_path VARCHAR(260) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id),
      title VARCHAR(160) NOT NULL,
      message TEXT NOT NULL,
      read_at TIMESTAMPTZ NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await seedDefaults();
}

async function seedDefaults() {
  const usersCount = await query<{ total: string }>("SELECT COUNT(*) AS total FROM users");
  if (Number(usersCount[0].total) === 0) {
    const professorHash = await bcrypt.hash("professor123", 10);
    const coordHash = await bcrypt.hash("coordenacao123", 10);
    await query(
      `INSERT INTO users (name, email, password_hash, role)
       VALUES (@professorName, @professorEmail, @professorHash, 'professor'),
              (@coordinatorName, @coordinatorEmail, @coordinatorHash, 'coordenacao')`,
      {
        professorName: "Professor Demo",
        professorEmail: "professor@senai.local",
        professorHash,
        coordinatorName: "Coordenacao Demo",
        coordinatorEmail: "coordenacao@senai.local",
        coordinatorHash: coordHash,
      },
    );
  }

  const centersCount = await query<{ total: string }>("SELECT COUNT(*) AS total FROM cost_centers");
  if (Number(centersCount[0].total) === 0) {
    await query(
      `INSERT INTO cost_centers (code, name)
       VALUES ('CC-ADM', 'Administrativo'), ('CC-LAB', 'Laboratorios'), ('CC-DOC', 'Docencia')`,
    );
  }
}
